add playlist func
desska/PlaylistMaker pull request #18
Opened 2024-07-16 07:10 UTC by desska

2024-07-16 20:16 UTC, DmitrijEgorow requested changes

2024-07-16 20:16 UTC, DmitrijEgorow commented on app/build.gradle
> +        enabled = true
Зачем? Может, без него?

> In many cases, [view binding](https://developer.android.com/topic/libraries/view-binding) can provide the same benefits as data binding with simpler implementation and better performance. If you are using data binding primarily to replace findViewById() calls, consider using view binding instead.

[https://developer.android.com/topic/libraries/data-binding](https://developer.android.com/topic/libraries/data-binding)

2024-07-16 20:16 UTC, DmitrijEgorow commented on app/build.gradle
>      buildFeatures {
Лишняя пустая строка перед viewBinding

2024-07-16 20:16 UTC, DmitrijEgorow commented on app/src/main/java/com/practicum/playlistmaker/data/db/PlaylistEntity.kt
> +    var name: String = "",
Лучше оставить в [data class неизменяемые свойства](https://www.reddit.com/r/Kotlin/comments/qibnqc/comment/hijhupt/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)

2024-07-16 20:16 UTC, DmitrijEgorow commented on app/src/main/java/com/practicum/playlistmaker/di/InteractorModule.kt
> +    single<NewListInteractor> {
Почему single, а не factory?

2024-07-16 20:16 UTC, DmitrijEgorow commented on app/src/main/java/com/practicum/playlistmaker/newlist/domain/FileService.kt
> +import android.net.Uri
Если это domain-слой, то без Android классов

2024-07-16 20:16 UTC, DmitrijEgorow commented on app/src/main/java/com/practicum/playlistmaker/newlist/domain/entity/Playlist.kt
> +    val qty: Int = 0
Что такое "qty"? Буквы бесплатные)

2024-07-16 20:16 UTC, DmitrijEgorow commented on app/src/main/java/com/practicum/playlistmaker/player/domain/entity/BottomSheetState.kt
> +    object COLLAPSED: BottomSheetState
А в других местах объекты не через caps lock, стоит унифицировать

2024-07-16 20:16 UTC, DmitrijEgorow commented on app/src/main/java/com/practicum/playlistmaker/player/ui/PlayerFragment.kt
> +        const val CLICK_DEBOUNCE_DELAY = 1000L
companion обычно идёт в конце, здесь он в случайном месте посередине класса

Подробнее описано в [документации](https://kotlinlang.org/docs/coding-conventions.html#class-layout)

2024-07-16 20:16 UTC, DmitrijEgorow commented on app/src/main/java/com/practicum/playlistmaker/player/ui/PlayerFragment.kt
> +        binding.playerArtistName.text = track.artistName
```suggestion
        with(binding) {
                playerTrackName.text = track.trackName
                playerArtistName.text = track.artistName
                ...
```

2024-07-16 20:16 UTC, DmitrijEgorow commented on app/src/main/res/layout/fragment_new_list.xml
> +            android:id="@+id/createButton"
Иной стиль написания идентификатора

2024-07-16 20:17 UTC, DmitrijEgorow commented
[Нарушение принципа сокрытия данных, кто угодно может поменять значение поля, что приведет к неконсистентному состоянию](https://github.com/desska/PlaylistMaker/blob/2b717b9fe21ee5e7c90fc4413620c3a2c64d131d/app/src/main/java/com/practicum/playlistmaker/App.kt#L15)

2024-07-16 20:28 UTC, DmitrijEgorow commented
Белый курсор на белом фоне плохо смотрится

![Screenshot_20240716_223554](https://github.com/user-attachments/assets/e22147ad-4d90-4099-8d89-08dd73b0d0d2)

Здесь, наверное, тоже можно поменять на синий, как сейчас сделано на экране поиска
![Screenshot_20240716_223624](https://github.com/user-attachments/assets/0489606d-5c8a-4d15-b1c7-b22916601fcd)

2024-07-16 20:29 UTC, DmitrijEgorow commented
Разметка не адаптируется под маленкьие диагонали, нужно масштабировать плейсхолдер и сохранять соотношение под квадрат
<img width="145" alt="Screenshot 2024-07-16 at 22 37 33" src="https://github.com/user-attachments/assets/a1b564f2-d65d-4355-a944-b787bbcec3cc">

2024-07-16 20:29 UTC, DmitrijEgorow commented
Неправильный цвет у progress bar

![Screenshot_20240716_223904](https://github.com/user-attachments/assets/e6ae6444-2aad-4864-b32d-026b1367d371)

2024-07-16 20:30 UTC, DmitrijEgorow commented
Стоит обрезать под квадрат и закруглять углы

![Screenshot_20240716_223951](https://github.com/user-attachments/assets/f2ed164c-8e03-4892-babe-b3e67d605c9d)

2024-07-16 20:31 UTC, DmitrijEgorow commented
Нет воздуха между обложкой и названием плейлиста
![Screenshot_20240716_224011](https://github.com/user-attachments/assets/425b3312-2a5b-4fcc-ab17-698ac2bf4a8b)

2024-07-16 20:32 UTC, DmitrijEgorow commented
Фиолетовый не входит в цветовую палитру приложения

![Screenshot_20240716_224108](https://github.com/user-attachments/assets/b338c7c4-c41a-431a-b988-fa0f7a7bb84c)

2024-07-16 20:34 UTC, DmitrijEgorow commented
Раз поисковый запрос не изменился, я бы не делал моргание списка


https://github.com/user-attachments/assets/5d47ee6e-5b4c-49f1-a601-f0d38a43d563

2024-07-17 00:37 UTC, desska commented on app/build.gradle
> +        enabled = true
пока оставлю так - используется в new list для https://developer.android.com/topic/libraries/data-binding/two-way

2024-07-17 01:48 UTC, desska commented
> Неправильный цвет у progress bar
> 
> ![Screenshot_20240716_223904](https://private-user-images.githubusercontent.com/36837067/349266039-e6ae6444-2aad-4864-b32d-026b1367d371.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNzU5MDMsIm5iZiI6MTcyMTE3NTYwMywicGF0aCI6Ii8zNjgzNzA2Ny8zNDkyNjYwMzktZTZhZTY0NDQtMmFhZC00ODY0LWIzMmQtMDI2YjEzNjdkMzcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDAwMjAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyZGUzZDY2MzI1MDk1NzVhOWRiZDBhYjdiZjZhZDEwNWIzYjY5MjMyYmM5ZTA4MzY3ZTc1NTM0NGMwZTY2ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pQFrVavfB8zVE62h4xu_6KjN5s7wk1TlSZ0OXk_JhEU)

Тут прошу уточнить: по макету https://www.figma.com/design/d4Joi0gI651J8vzYS1j6Vt/Loading.-Playlist-maker-(YP)?node-id=1-580&t=2uhSuuhbvVgsqmAZ-0 должно сходиться.

2024-07-17 13:54 UTC, DmitrijEgorow commented
> Стоит обрезать под квадрат и закруглять углы
> 
> ![Screenshot_20240716_223951](https://private-user-images.githubusercontent.com/36837067/349266168-f2ed164c-8e03-4892-babe-b3e67d605c9d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMjQyNjYsIm5iZiI6MTcyMTIyMzk2NiwicGF0aCI6Ii8zNjgzNzA2Ny8zNDkyNjYxNjgtZjJlZDE2NGMtOGUwMy00ODkyLWJhYmUtYjNlNjdkNjA1YzlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDEzNDYwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NGM4ZDgxMDAyZTllNGYyMWYxZTNjZDFjNmYyNGYwOTNmMjM1YzE0MDkxODE3NjY1ZWYxNjViMWJlNmQxMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9qzW93gQ4TqYU14Yi9GPLL6FL3PUBXg7WdRewTctwV4)

Предлагал обрезать под квадрат, а не ужимать, но ладно...

2024-07-17 13:55 UTC, DmitrijEgorow commented
> > Неправильный цвет у progress bar
> > ![Screenshot_20240716_223904](https://private-user-images.githubusercontent.com/36837067/349266039-e6ae6444-2aad-4864-b32d-026b1367d371.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNzU5MDMsIm5iZiI6MTcyMTE3NTYwMywicGF0aCI6Ii8zNjgzNzA2Ny8zNDkyNjYwMzktZTZhZTY0NDQtMmFhZC00ODY0LWIzMmQtMDI2YjEzNjdkMzcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDAwMjAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyZGUzZDY2MzI1MDk1NzVhOWRiZDBhYjdiZjZhZDEwNWIzYjY5MjMyYmM5ZTA4MzY3ZTc1NTM0NGMwZTY2ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pQFrVavfB8zVE62h4xu_6KjN5s7wk1TlSZ0OXk_JhEU)
> 
> Тут прошу уточнить: по макету https://www.figma.com/design/d4Joi0gI651J8vzYS1j6Vt/Loading.-Playlist-maker-(YP)?node-id=1-580&t=2uhSuuhbvVgsqmAZ-0 должно сходиться.

вот
<img width="950" alt="Screenshot 2024-07-17 at 16 50 27" src="https://github.com/user-attachments/assets/7eb195b1-2ee1-4adc-b8fa-aa5f4cc4cc34">

2024-07-17 23:23 UTC, desska commented
> > > Неправильный цвет у progress bar
> > > ![Screenshot_20240716_223904](https://private-user-images.githubusercontent.com/36837067/349266039-e6ae6444-2aad-4864-b32d-026b1367d371.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNzU5MDMsIm5iZiI6MTcyMTE3NTYwMywicGF0aCI6Ii8zNjgzNzA2Ny8zNDkyNjYwMzktZTZhZTY0NDQtMmFhZC00ODY0LWIzMmQtMDI2YjEzNjdkMzcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDAwMjAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyZGUzZDY2MzI1MDk1NzVhOWRiZDBhYjdiZjZhZDEwNWIzYjY5MjMyYmM5ZTA4MzY3ZTc1NTM0NGMwZTY2ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pQFrVavfB8zVE62h4xu_6KjN5s7wk1TlSZ0OXk_JhEU)
> > 
> > 
> > Тут прошу уточнить: по макету https://www.figma.com/design/d4Joi0gI651J8vzYS1j6Vt/Loading.-Playlist-maker-(YP)?node-id=1-580&t=2uhSuuhbvVgsqmAZ-0 должно сходиться.
> 
> вот <img alt="Screenshot 2024-07-17 at 16 50 27" width="950" src="https://private-user-images.githubusercontent.com/36837067/349527515-7eb195b1-2ee1-4adc-b8fa-aa5f4cc4cc34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNTg3MDMsIm5iZiI6MTcyMTI1ODQwMywicGF0aCI6Ii8zNjgzNzA2Ny8zNDk1Mjc1MTUtN2ViMTk1YjEtMmVlMS00YWRjLWI4ZmEtYWE1ZjRjYzRjYzM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDIzMjAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhNGVhM2IyMzQxNjhiOTUxNzhmOGVmMzlkOTE2ODdhMTdlMDY5NDUyNzcwY2FmYjQwMGFkZWIxODZjN2RjYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.smTiFIU0BHsCk_jtbjtr9MJ0R1_7ebSnQ7I1dwSIILI">

Поправил. По какой то причине фигма показывает значение цвета в макете 6200EE , а для меня эти цвета +- одинаковые

2024-07-18 09:24 UTC, merged